### ISSUE TITLE
Pages source meta tag

### ISSUE THREAD

**Issue by jtagcat** [kidonng/cherry#14]
It seems that all sites include a link to the source with `<meta content="https://github.com/username/repo" name="generator">`. Use that instead. Also supports non-gh.io domains.

**Comment by kidonng** [comment]
I don't think `<meta name="generator">` is something added by GitHub and present on all site using GitHub Pages. GitHub's native pages build gives something like `<meta name="generator" content="Jekyll v3.9.0">`.

Can you give an example?

**Comment by jtagcat** [comment]
Huh, went through a bunch of pages, didn't find a single one, even not on the ones on *.github.io.

Maybe it's been since removed.
