### ISSUE TITLE
GitHub: `hideOwnPackagesTab` option hides packages in all profiles, not only own

### ISSUE THREAD

**Issue by darkred** [kidonng/cherry#15]
I've noticed in [GitHub](https://github.com/kidonng/cherry/blob/master/styles/github.user.css) userstyle
that the `hideOwnPackagesTab" option hides packages in all profiles, not only my own.
I tested it my own profile page https://github.com/darkred as well as [yours](https://github.com/kidonng) and various others:
<details>
<summary>screenshots:</summary>

![2021-06-16_161818](https://user-images.githubusercontent.com/723651/122227704-cdb1f780-cebf-11eb-889b-ae16a6ea5a63.jpg) ![2021-06-16_162052](https://user-images.githubusercontent.com/723651/122227101-42d0fd00-cebf-11eb-80a3-0ed2eee49e99.jpg)

![2021-06-16_162109](https://user-images.githubusercontent.com/723651/122227252-67c57000-cebf-11eb-811f-c8aa1f78b112.jpg) ![2021-06-16_162123](https://user-images.githubusercontent.com/723651/122227051-36e53b00-cebf-11eb-88e6-4f834a2fd944.jpg)
</details>

Also there's a typo in its description:
![2021-06-16_160715](https://user-images.githubusercontent.com/723651/122225373-aeb26600-cebd-11eb-86d4-4d560663397b.jpg)
`Pacakges` --> `Packages`

&nbsp;
Concluding, maybe it would be better to drop the feature (and option) altogether,
because of the Refined GitHub's feature [`hide-zero-packages`](https://github.com/sindresorhus/refined-github/blob/main/source/features/hide-zero-packages.tsx) (and its improvement, via this ongoing [PR](https://github.com/sindresorhus/refined-github/pull/4481)).
I believe that hiding the package tab when it's zero (in any profile) is what's helpful to the user.
When viewing my own profile, if I have uploaded packages, I want to be able to see them.

Thank you for your work!

PS. Using Stylus 1.5.17 with Chrome 91/Firefox 89

**Comment by darkred** [comment]
@kidonng I see that the `hide-zero-packages` feature has been eventually removed  https://github.com/sindresorhus/refined-github/pull/4487 , 

> Profiles don't include the packages count anymore(?) and it's not worth an extra API call for now.

so I'm closing this.

**Comment by kidonng** [comment]
Sorry for not getting to this in time. I have removed "own" in the description.

I don't want to drop this because few people actually use GitHub Packages and it's frustrating to see it all the time.

**Comment by darkred** [comment]
Thanks a lot for responding. I understand, you are right. For most of the cases there are no packages. It just gets in the way for the vast majority of profiles.


&nbsp;
Btw, could you please change in https://github.com/kidonng/cherry/blob/ca316903213e44722c029a3363665765b7162e0c/styles/github.user.css#L16

`Pacakges` --> `Packages`

**Comment by kidonng** [comment]
I keep misspelling that word 🤦 Thanks for spotting it!
